add_newline = false
command_timeout = 1200

format = "$directory$git_branch$git_status$python$nodejs$golang$rust$kubernetes$cmd_duration$character"
right_format = "$jobs$time"

[directory]
style = "bold #61afef"
truncation_length = 4
truncate_to_repo = true
format = "[$path]($style) "
read_only = " "

[git_branch]
symbol = " "
style = "bold #98c379"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #e5c07b"
format = "([$all_status$ahead_behind]($style) )"
conflicted = ""
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕${count}"
up_to_date = ""
untracked = "?${count}"
stashed = "${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[python]
symbol = " "
style = "bold #c678dd"
format = "via [$symbol$version(\\($virtualenv\\))]($style) "

[nodejs]
symbol = " "
style = "bold #98c379"
format = "via [$symbol$version]($style) "

[golang]
symbol = " "
style = "bold #56b6c2"
format = "via [$symbol$version]($style) "

[rust]
symbol = " "
style = "bold #d19a66"
format = "via [$symbol$version]($style) "

[kubernetes]
symbol = "⎈ "
style = "bold #61afef"
format = "on [$symbol$context(\\($namespace\\))]($style) "
disabled = false

[cmd_duration]
min_time = 2000
format = "took [$duration]($style) "
style = "bold #e5c07b"
show_milliseconds = true
show_notifications = true
min_time_to_notify = 15000

[jobs]
symbol = " "
style = "bold #abb2bf"
number_threshold = 1
format = "[$symbol$number]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "bold #5c6370"
format = "[$time]($style)"

[character]
success_symbol = "[❯](bold #98c379)"
error_symbol = "[✗](bold #e06c75)"
vimcmd_symbol = "[❮](bold #e5c07b)"
